behaviors:
  ArmAgentBehavior:
    trainer_type: ppo
    max_steps: 50000000 
    time_horizon: 1    
    summary_freq: 10000
    checkpoint_interval: 50000
    threaded: true

    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2

    reward_signals:
      extrinsic:
        gamma: 1.0
        strength: 1.0